### ISSUE TITLE
Baudrate

### ISSUE THREAD

**Issue by kinglevel** [kjellegafvelin/SimpleDyno#1]
Is it possible to increase the COM baud rate?

**Comment by kjellegafvelin** [comment]
Is 115200 to slow? I suppose you could increase it as what I have read it is possible. I'm not doing any active development on this right now. But if you want to modify it you will find the baud rates at https://github.com/kjellegafvelin/SimpleDyno/blob/master/Main.vb#L2838.

**Comment by kinglevel** [comment]
Yes i found it too slow for my setup.
The COM messages created noise on the variables if the baudrate were too slow.

I made my own build with 2 000 000, and it worked.
No prior knowledge of vb. but it magically worked great just adding more rates.

**Comment by kjellegafvelin** [comment]
Closing this issue as I will archive this repo.
