### ISSUE TITLE
Error reading COM port

### ISSUE THREAD

**Issue by Armini-inv** [kjellegafvelin/SimpleDyno#2]
Hi, does communication with COM port works for you? i downloaded 2 version of this software one the 6.5.1 version from the original website and one that u have worked on, but non of them can communicate with COM port in win7 and win10. DamoRC said its be cause of some changes in win7 and higher version of windows. is there anyway to solve this problem? thx

**Comment by kjellegafvelin** [comment]
Yes, it does. I have had it run on Win 10 without any issues, although it was a while ago so I don't know if it still works.

**Comment by Armini-inv** [comment]
hmmm well the software itself works good for me the only problem is that i cant connect to COM port to get data from ardoino. can u plz check it again to see if u can connect to COM port? i really need this software ill be really thankful if u do me this favor. 
btw the same problem is also reported here   https://www.tapatalk.com/groups/simpledyno/this-software-is-not-support-in-window-8-1-t161.html

**Comment by randall-tech** [comment]
Hi guys,
I have just tested this and I can confirm that it does work on Windows 10.

@Armini-inv Make sure that the baud rate you have selected in SimpleDyno is the same as the baud you have in the Arduino sketch under "SerialBegin(9600)". The default in the Arduino sketch is 9600 baud. If this is not the same baud on both SimpleDyno and the Arduino sketch, it wont work. Also, I am just using a generic Arduino (Sparkfun RedBoard).

**Comment by pienari** [comment]
Hi.
Greetings from Finland.
I started to make new dyno and i get same "Error reading COM port" win10 and pure install win XP pro sp3.
I have tested versions 6.5 , 6.5.1 and 6.5.3
I got genuine Arduino UNO and Arduino Leonardo and both same issue.
Arduino serial monitor can read serial data fine so it is not a problem.

**Comment by pienari** [comment]
Problem solved.
I simply chanced fuses with Atmelstudio and problem is in xtal settings.
Some reason program cant understand if internal xtal is used.
So i programmed external 8- Mhz and UNO works fine now.
How i can set Leonardo xtal to external?.

**Comment by kjellegafvelin** [comment]
Closing this issue as I will archive this repo.
