### ISSUE TITLE
Non linear curve fitting

### ISSUE THREAD

**Issue by lassi-niemisto** [kjellegafvelin/SimpleDyno#3]
Official simpledyno release 6.5.1 https://sites.google.com/site/simpledyno/file-cabinet supports RPM1 curve fitting in MA Smooth mode.

However the source package available on the same site, as well as this repository includes the following in the Fit.vb:
```
        lblProgress.Text = "Fitting RPM1..."
        'DC 21JAN16 - Old code based on VBA source from Optimiz.xla
        'Note that the old code returns the function values for the fitted Y parameter
        'Call NonLin, sending the local copies of the data by ref
        'NonLin_fitting(x, y, fy, cmbWhichFit.SelectedIndex + 1, blnRPMFit)

        'DC 21JAN16 - New code based on the work of Rod Stephens - Used with permission of the Author
        'BestCoeffs is a generic list of type double and holds the coefficients of the polynomial solution
        'Points is a generic list of System.Drawing.PointF and is the raw X and Y data to be fit
        'Degree is an integer and represents the degree of the fit.
        'Original line is:
        ' BestCoeffs = FindPolynomialLeastSquaresFit(Points, degree)
        blnRPMFit = FindPolynomialLeastSquaresFit_NEW(x, y, fy, cmbWhichFit.SelectedIndex + 1)
```

So the MA Smooth mode has been commented out in the code as far as I can debgug it. Flipping the nonlin mode enabled and polynomial mode disabled allows it to perform similar to 6.5.1 binary release. 

I am not sure who is able to use the polynomial modes to anything. My use case is https://ardyno.weebly.com/ and the polynomial modes are clearly not useful for 2-stroke engine measurement purposes. Do you @kjellegafvelin have any idea about the history of this disappearance of nonlinear MA smoothing mode, and what is your use case if you are happy with the polynomial fitting?

**Comment by kjellegafvelin** [comment]
No, I don't have a clue about it. 

I will close this issue as I will archive this repo.
