### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by ckbliss49** [kjellegafvelin/SimpleDyno#4]
I want to take a shot at adding some of the missing functionality but cannot get the existing code to compile.  I have tried VS2012 and VS2022.  What version do I need?

Specifically, I want to add the ability to read torque directly from my dyno's strain  gauge via Arduino.  Would also like to specify things like RPM as numbers coming from the Arduino serial stream. My dyno is for electric motors and has a configurable stream of data in CDF already.

**Comment by ckbliss49** [comment]
One  message, "OxyPlot.WindowsForms.PlotView' is not defined." tells me we need to install some packages but they didn't for me.  After some searching, I found this...

To get the compile to work, we need to install NuGet OxyPlot core and winforms and LiveChat but was failing in VB2010 and 2012.  Discovered that the problem had to do with security settings to fix, I loaded up VS2012 and: 

Open package manager console in Visual Studio
Type: [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bOR [Net.SecurityProtocolType]::Tls12

This will change the connection security protocol to nuget as specified in this article: Deprecating TLS 1.0 and 1.1 on NuGet.org 
https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

It also made VS2010 work as an added bonus

**Comment by kjellegafvelin** [comment]
Closing this issue as I will archive this repo.
